version: '1.1'
services:
  nginx:
    container_name: nginx
    image: nginx
    build:
      context: .
      dockerfile: .gizlo-web/docker/nginx.dockerfile
    volumes:
      - ./dist:/usr/share/nginx/html
    ports:
      - "80:80"
      - "443:443"

    networks:
      - gizlo-network

  spring:
    container_name: gizlows
    image: gizlows
    build:
      context: ./gizlows/
      dockerfile: .gizlo-ws/Dockerfile
    ports:
      - "8082:8082"
    depends_on: 
      - mongodb
    networks:
      - gizlo-network
      
  #No authentication is provided here - JUST A DEMO! That would absolutely
  #be needed for a "real" application
  mongodb:
    container_name: mongodb
    image: mongo
    networks:
      - gizlo-network

networks:
  gizlo-network:
    driver: bridge